### ISSUE TITLE
Build failure on ubuntu

### ISSUE THREAD

**Issue by bensonhi** [ambiot/ambpro2_sdk#2]
I can build this project normally on my windows pc, but when I switch to ubuntu it shows below error when executing

`cmake --build . --target flash_nn`

error:
```
/home/ben/桌面/ambpro2_sdk-main/component/os/freertos/freertos_posix/lib/include/FreeRTOS_POSIX/time_gcc.h:35:22: fatal error: xlocale.h: No such file or directory
  #include <xlocale.h>

```

I tried to fix it by adding a link file but didn't work out
`sudo ln -s /usr/include/locale.h /usr/include/xlocale.h`

**Comment by S10143806H** [comment]
Dear @bensonhi,
Thanks for bringing this out. This has been a known issue. 
We will get back to you again once there is an update.
Thank you.

**Comment by HungTseLee** [comment]
Hi @bensonhi 
sorry, I can't reproduce it on my ubuntu pc.
could you provide the steps to reproduce it?

**Comment by HungTseLee** [comment]
clsoe this since no futher response
feel free to reopen it if threre is any question
