### ISSUE TITLE
JX-F37 is EOL

### ISSUE THREAD

**Issue by bgatti** [ambiot/ambpro2_sdk#6]
Could we include support for Camera Sensor which is in production? I am informed that the Sensor is End of Life. As such, no competent engineer can move forward with a new product on this code base until there production potential for a supported camera.

Here the product is no longer listed:
https://www.soinc.com.tw/product/introduction/22

refer to: https://github.com/ambiot/ambpro2_sdk/blob/main/project/realtek_amebapro2_v0_example/inc/sensor.h

**Comment by HungTseLee** [comment]
Hi @bgatti 
The sensor supported in SDK is JX-F37P, which is still in production!

**Comment by bgatti** [comment]
Great, thanks for the update.
